name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --workspace
    # Tests: we only run library and documentation tests (integration tests are using the remote server!)
    - name: Run tests (unittests)
      run: cargo test --lib --verbose --workspace
    - name: Run tests (documentation tests)
      run: cargo test --doc --verbose --workspace

    - name: Test cargo readme is generated
      run: |
        cargo install cargo-readme
        cargo readme > README.md
        git diff --exit-code README.md
