name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Release-plz
        run: |
          cargo install --locked release-plz
          cargo install --locked cargo-semver-checks
      - name: Release crate
        run: release-plz release --git-token $GITHUB_TOKEN --repo-url "https://github.com/IBM/${{ github.event.repository.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-plz-pr:
    name: Release-plz PR
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Release-plz
        run: |
          cargo install --locked release-plz
          cargo install --locked cargo-semver-checks
      - name: Create or update PR
        run: release-plz release-pr --git-token $GITHUB_TOKEN --repo-url "https://github.com/IBM/${{ github.event.repository.name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
